// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (message_id, file_name, file_size, content_type, storage_path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, message_id, file_name, file_size, content_type, storage_path, created_at
`

type CreateAttachmentParams struct {
	MessageID   pgtype.UUID `json:"message_id"`
	FileName    string      `json:"file_name"`
	FileSize    int64       `json:"file_size"`
	ContentType string      `json:"content_type"`
	StoragePath string      `json:"storage_path"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.MessageID,
		arg.FileName,
		arg.FileSize,
		arg.ContentType,
		arg.StoragePath,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileName,
		&i.FileSize,
		&i.ContentType,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const listMessageAttachments = `-- name: ListMessageAttachments :many
SELECT id, message_id, file_name, file_size, content_type, storage_path, created_at FROM attachments WHERE message_id = $1
`

func (q *Queries) ListMessageAttachments(ctx context.Context, messageID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listMessageAttachments, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileName,
			&i.FileSize,
			&i.ContentType,
			&i.StoragePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
