// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelMember = `-- name: AddChannelMember :exec
INSERT INTO channel_members (channel_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error {
	_, err := q.db.Exec(ctx, addChannelMember, arg.ChannelID, arg.UserID)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, description, is_private, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, is_private, created_by, created_at, updated_at
`

type CreateChannelParams struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	IsPrivate   bool        `json:"is_private"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.Description,
		arg.IsPrivate,
		arg.CreatedBy,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, description, is_private, created_by, created_at, updated_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByName = `-- name: GetChannelByName :one
SELECT id, name, description, is_private, created_by, created_at, updated_at FROM channels WHERE name = $1
`

func (q *Queries) GetChannelByName(ctx context.Context, name string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByName, name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelLastRead = `-- name: GetChannelLastRead :one
SELECT last_read_at FROM channel_members
WHERE channel_id = $1 AND user_id = $2
`

type GetChannelLastReadParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetChannelLastRead(ctx context.Context, arg GetChannelLastReadParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getChannelLastRead, arg.ChannelID, arg.UserID)
	var last_read_at pgtype.Timestamptz
	err := row.Scan(&last_read_at)
	return last_read_at, err
}

const isChannelMember = `-- name: IsChannelMember :one
SELECT EXISTS(SELECT 1 FROM channel_members WHERE channel_id = $1 AND user_id = $2)
`

type IsChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsChannelMember(ctx context.Context, arg IsChannelMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelMember, arg.ChannelID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listChannelMembers = `-- name: ListChannelMembers :many
SELECT u.id, u.google_id, u.email, u.display_name, u.avatar_url, u.created_at, u.updated_at FROM users u
JOIN channel_members cm ON u.id = cm.user_id
WHERE cm.channel_id = $1
ORDER BY u.display_name
`

func (q *Queries) ListChannelMembers(ctx context.Context, channelID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listChannelMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicChannels = `-- name: ListPublicChannels :many
SELECT id, name, description, is_private, created_by, created_at, updated_at FROM channels WHERE is_private = false ORDER BY name
`

func (q *Queries) ListPublicChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listPublicChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChannels = `-- name: ListUserChannels :many
SELECT c.id, c.name, c.description, c.is_private, c.created_by, c.created_at, c.updated_at FROM channels c
JOIN channel_members cm ON c.id = cm.channel_id
WHERE cm.user_id = $1
ORDER BY c.name
`

func (q *Queries) ListUserChannels(ctx context.Context, userID pgtype.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listUserChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChannelMember = `-- name: RemoveChannelMember :exec
DELETE FROM channel_members WHERE channel_id = $1 AND user_id = $2
`

type RemoveChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveChannelMember(ctx context.Context, arg RemoveChannelMemberParams) error {
	_, err := q.db.Exec(ctx, removeChannelMember, arg.ChannelID, arg.UserID)
	return err
}

const updateChannelLastRead = `-- name: UpdateChannelLastRead :exec
UPDATE channel_members SET last_read_at = now()
WHERE channel_id = $1 AND user_id = $2
`

type UpdateChannelLastReadParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateChannelLastRead(ctx context.Context, arg UpdateChannelLastReadParams) error {
	_, err := q.db.Exec(ctx, updateChannelLastRead, arg.ChannelID, arg.UserID)
	return err
}
