// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddConversationMemberParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.Exec(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations DEFAULT VALUES
RETURNING id, created_at
`

func (q *Queries) CreateConversation(ctx context.Context) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation)
	var i Conversation
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const findExistingConversation = `-- name: FindExistingConversation :one
SELECT cm1.conversation_id FROM conversation_members cm1
WHERE cm1.user_id = $1
AND cm1.conversation_id IN (
    SELECT cm2.conversation_id FROM conversation_members cm2
    WHERE cm2.user_id = $2
)
AND (SELECT COUNT(*) FROM conversation_members cm3 WHERE cm3.conversation_id = cm1.conversation_id) = 2
LIMIT 1
`

type FindExistingConversationParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

func (q *Queries) FindExistingConversation(ctx context.Context, arg FindExistingConversationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findExistingConversation, arg.UserID, arg.UserID_2)
	var conversation_id pgtype.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getConversationLastRead = `-- name: GetConversationLastRead :one
SELECT last_read_at FROM conversation_members
WHERE conversation_id = $1 AND user_id = $2
`

type GetConversationLastReadParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetConversationLastRead(ctx context.Context, arg GetConversationLastReadParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getConversationLastRead, arg.ConversationID, arg.UserID)
	var last_read_at pgtype.Timestamptz
	err := row.Scan(&last_read_at)
	return last_read_at, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS(SELECT 1 FROM conversation_members WHERE conversation_id = $1 AND user_id = $2)
`

type IsConversationMemberParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationMembers = `-- name: ListConversationMembers :many
SELECT u.id, u.google_id, u.email, u.display_name, u.avatar_url, u.created_at, u.updated_at FROM users u
JOIN conversation_members cm ON u.id = cm.user_id
WHERE cm.conversation_id = $1
ORDER BY u.display_name
`

func (q *Queries) ListConversationMembers(ctx context.Context, conversationID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT c.id, c.created_at FROM conversations c
JOIN conversation_members cm ON c.id = cm.conversation_id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) ListUserConversations(ctx context.Context, userID pgtype.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationLastRead = `-- name: UpdateConversationLastRead :exec
UPDATE conversation_members SET last_read_at = now()
WHERE conversation_id = $1 AND user_id = $2
`

type UpdateConversationLastReadParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateConversationLastRead(ctx context.Context, arg UpdateConversationLastReadParams) error {
	_, err := q.db.Exec(ctx, updateConversationLastRead, arg.ConversationID, arg.UserID)
	return err
}
