// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadChannelMessages = `-- name: CountUnreadChannelMessages :one
SELECT COUNT(*) FROM messages m
WHERE m.channel_id = $1
AND m.created_at > $2
AND m.parent_id IS NULL
`

type CountUnreadChannelMessagesParams struct {
	ChannelID pgtype.UUID        `json:"channel_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountUnreadChannelMessages(ctx context.Context, arg CountUnreadChannelMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadChannelMessages, arg.ChannelID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadConversationMessages = `-- name: CountUnreadConversationMessages :one
SELECT COUNT(*) FROM messages m
WHERE m.conversation_id = $1
AND m.created_at > $2
AND m.parent_id IS NULL
`

type CountUnreadConversationMessagesParams struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountUnreadConversationMessages(ctx context.Context, arg CountUnreadConversationMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadConversationMessages, arg.ConversationID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (user_id, channel_id, conversation_id, parent_id, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, channel_id, conversation_id, parent_id, content, is_edited, created_at, updated_at
`

type CreateMessageParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	ChannelID      pgtype.UUID `json:"channel_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Content        string      `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.UserID,
		arg.ChannelID,
		arg.ConversationID,
		arg.ParentID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.ConversationID,
		&i.ParentID,
		&i.Content,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, user_id, channel_id, conversation_id, parent_id, content, is_edited, created_at, updated_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.ConversationID,
		&i.ParentID,
		&i.Content,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelMessages = `-- name: ListChannelMessages :many
SELECT m.id, m.user_id, m.channel_id, m.conversation_id, m.parent_id, m.content, m.is_edited, m.created_at, m.updated_at, u.display_name as author_name, u.avatar_url as author_avatar,
       (SELECT COUNT(*) FROM messages r WHERE r.parent_id = m.id) as reply_count
FROM messages m
JOIN users u ON m.user_id = u.id
WHERE m.channel_id = $1 AND m.parent_id IS NULL
ORDER BY m.created_at ASC
`

type ListChannelMessagesRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Content        string             `json:"content"`
	IsEdited       bool               `json:"is_edited"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   string             `json:"author_avatar"`
	ReplyCount     int64              `json:"reply_count"`
}

func (q *Queries) ListChannelMessages(ctx context.Context, channelID pgtype.UUID) ([]ListChannelMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChannelMessages, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelMessagesRow{}
	for rows.Next() {
		var i ListChannelMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.ConversationID,
			&i.ParentID,
			&i.Content,
			&i.IsEdited,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT m.id, m.user_id, m.channel_id, m.conversation_id, m.parent_id, m.content, m.is_edited, m.created_at, m.updated_at, u.display_name as author_name, u.avatar_url as author_avatar,
       (SELECT COUNT(*) FROM messages r WHERE r.parent_id = m.id) as reply_count
FROM messages m
JOIN users u ON m.user_id = u.id
WHERE m.conversation_id = $1 AND m.parent_id IS NULL
ORDER BY m.created_at ASC
`

type ListConversationMessagesRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Content        string             `json:"content"`
	IsEdited       bool               `json:"is_edited"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   string             `json:"author_avatar"`
	ReplyCount     int64              `json:"reply_count"`
}

func (q *Queries) ListConversationMessages(ctx context.Context, conversationID pgtype.UUID) ([]ListConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, listConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationMessagesRow{}
	for rows.Next() {
		var i ListConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.ConversationID,
			&i.ParentID,
			&i.Content,
			&i.IsEdited,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadReplies = `-- name: ListThreadReplies :many
SELECT m.id, m.user_id, m.channel_id, m.conversation_id, m.parent_id, m.content, m.is_edited, m.created_at, m.updated_at, u.display_name as author_name, u.avatar_url as author_avatar
FROM messages m
JOIN users u ON m.user_id = u.id
WHERE m.parent_id = $1
ORDER BY m.created_at ASC
`

type ListThreadRepliesRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Content        string             `json:"content"`
	IsEdited       bool               `json:"is_edited"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   string             `json:"author_avatar"`
}

func (q *Queries) ListThreadReplies(ctx context.Context, parentID pgtype.UUID) ([]ListThreadRepliesRow, error) {
	rows, err := q.db.Query(ctx, listThreadReplies, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadRepliesRow{}
	for rows.Next() {
		var i ListThreadRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.ConversationID,
			&i.ParentID,
			&i.Content,
			&i.IsEdited,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages SET content = $2, is_edited = true, updated_at = now()
WHERE id = $1
RETURNING id, user_id, channel_id, conversation_id, parent_id, content, is_edited, created_at, updated_at
`

type UpdateMessageParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.ConversationID,
		&i.ParentID,
		&i.Content,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
