// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID          pgtype.UUID        `json:"id"`
	MessageID   pgtype.UUID        `json:"message_id"`
	FileName    string             `json:"file_name"`
	FileSize    int64              `json:"file_size"`
	ContentType string             `json:"content_type"`
	StoragePath string             `json:"storage_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Channel struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	IsPrivate   bool               `json:"is_private"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ChannelMember struct {
	ChannelID  pgtype.UUID        `json:"channel_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
	LastReadAt pgtype.Timestamptz `json:"last_read_at"`
}

type Conversation struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ConversationMember struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	LastReadAt     pgtype.Timestamptz `json:"last_read_at"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Content        string             `json:"content"`
	IsEdited       bool               `json:"is_edited"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Reaction struct {
	ID        pgtype.UUID        `json:"id"`
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	GoogleID    string             `json:"google_id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
