// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReaction = `-- name: AddReaction :one
INSERT INTO reactions (message_id, user_id, emoji)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, user_id, emoji) DO NOTHING
RETURNING id, message_id, user_id, emoji, created_at
`

type AddReactionParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (Reaction, error) {
	row := q.db.QueryRow(ctx, addReaction, arg.MessageID, arg.UserID, arg.Emoji)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const listMessageReactions = `-- name: ListMessageReactions :many
SELECT r.emoji, r.user_id, u.display_name
FROM reactions r
JOIN users u ON r.user_id = u.id
WHERE r.message_id = $1
ORDER BY r.created_at
`

type ListMessageReactionsRow struct {
	Emoji       string      `json:"emoji"`
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) ListMessageReactions(ctx context.Context, messageID pgtype.UUID) ([]ListMessageReactionsRow, error) {
	rows, err := q.db.Query(ctx, listMessageReactions, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageReactionsRow{}
	for rows.Next() {
		var i ListMessageReactionsRow
		if err := rows.Scan(&i.Emoji, &i.UserID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM reactions WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}
